### ISSUE TITLE
[Bug] 會與骰子大師v1.3.1衝突

### ISSUE THREAD

**Issue by Zhen-Bo** [NothingNullNull/LOMSave#1]
## [環境]
骰子大師: v1.3.1
LOMSave: 2024619

## [步驟]
1. 安裝骰子大師 v1.3.1
2. 下載 LOMSave.dll 並把該檔案放入 `BepInEx\plugins` 資料夾內
3. 開啟遊戲

## [預期結果]
1. 可以隨時存檔
2. 按下 tab 可以呼出骰子大師菜單, 且可以選擇觸發事件

## [實際結果]
1. 可以隨時存檔
2. 骰子大師的 tab 菜單失去作用
![PixPin_2024-06-20_00-15-37](https://github.com/NothingNullNull/LOMSave/assets/30999421/d62ccd52-8d1b-4f85-b51f-9bb6ce9f6020)

## [備註]
反正這遊戲沒英文估計也不會有外國人用, 就打算用中文回報就好了

**Comment by NothingNullNull** [comment]
我瞎了，看错了你的描述，抱歉。我看看。

**Comment by NothingNullNull** [comment]
620版本已解决，感谢提交
